### ISSUE TITLE
Sorry, I didn't see how to use it

### ISSUE THREAD

**Issue by lly0414** [pd4d10/vite-plugin-svgr#1]
Could you tell me how I should use him, I downloaded him and loaded it into the plug-in, but the vite was wrong

**Comment by pd4d10** [comment]
Could you please provide a reproducible example?

**Comment by lly0414** [comment]
I wish I could use svgr like I did in webpack, but I don't know how to use it
## Now I use it like this
```js
import * as React from "react"

function SvgComponent(props) {
  return (
    <svg
      width={48}
      height={1}
      viewBox="0 0 48 1"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <title>{"Rectangle 5"}</title>
      <path d="M0 0h48v1H0z" fill="#063855" fillRule="evenodd" />
    </svg>
  )
}

export default SvgComponent
```
```js
import SvgComponentfrom './svg/SvgComponent'
```

**Comment by lly0414** [comment]
What else do I need to do besides import ``vite-plugin-svgr``? I'm not skilled at using **vite**, I'm sorry

**Comment by pd4d10** [comment]
You can directly import SVG files as [create-react-app](https://create-react-app.dev/docs/adding-images-fonts-and-files#adding-svgs) does:

```js
import { ReactComponent as Logo } from './logo.svg';
```

**Comment by pd4d10** [comment]
README updated: https://github.com/pd4d10/vite-plugin-svgr#usage

**Comment by lly0414** [comment]
I can use it, thank you!
