### ISSUE TITLE
Pass svgr config options

### ISSUE THREAD

**Issue by Tobijudah** [pd4d10/vite-plugin-svgr#10]
Hey @pd4d10 great work on the plugin. I was wondering there's a way to pass svgr config options like
`{
  "ref": true
}`
to pass a ref to my component.

Or is there a way to pass refs without that?

**Comment by IanVS** [comment]
Similarly, I want to turn on `icon: true`, but it seems there's no way.  I see a todo to add options (https://github.com/pd4d10/vite-plugin-svgr/blob/83b07cb59a996e4e2b3ba29990e0db0f9c6c4fc6/src/index.ts#L6), is that something that's being worked on, or would you accept a PR?
