### ISSUE TITLE
adding the alt attribute 

### ISSUE THREAD

**Issue by apmavrin** [pd4d10/vite-plugin-svgr#103]
Would it make sense adding an optional `alt` attribute to the ReactoComponent to support the accessibility?

**client.d.ts**

```
const ReactComponent: React.FunctionComponent<
    React.ComponentProps<"svg"> & { title?: string, **alt?: string** }
>;
```

**Comment by paolostyle** [comment]
`alt` attribute is not a valid attribute on an `<svg>` element. The `title` prop essentially does what you want, it's equivalent to `alt` on `<img>`. So I'm not sure what you're trying to achieve but it's probably wrong.

**Comment by pypp** [comment]
> `alt` attribute is not a valid attribute on an `<svg>` element. The `title` prop essentially does what you want, it's equivalent to `alt` on `<img>`. So I'm not sure what you're trying to achieve but it's probably wrong.

How would you pass a title ? I can’t find a way to do it.
