### ISSUE TITLE
Include all SVG files, without the `?react` doesn't work

### ISSUE THREAD

**Issue by sanjarcode** [pd4d10/vite-plugin-svgr#107]
Note: Plain JS project (not TS).
Can we omit the need to add `?react` at the end of every SVG import?

## Current situation
```jsx
// works

export default defineConfig({
  plugins: [react(), svgr()], // no params
  base: `/${viteBaseName}/`,
});

import MyIcon from "../MyIcon.svg?react";   //  has `?react`

<MyIcon /> // works
```

## Goal situation
I used the include option in `vite.config.js`, but that didn't work:
```js
// this doesn't works
export default defineConfig({
  plugins: [
    react(),
    svgr({
      include: "**/*.svg", // params
    }),
  ],
  base: `/${viteBaseName}/`,
});

import MyIcon from "../MyIcon.svg";  // no `?react`
<MyIcon /> // doesn't work

/*
DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/vite-react-js-template/src/MyIcon.svg') is not a valid name
*/
```

How to fix this? I think some default parameters may be missing in this second case. If yes, can we use callback pattern such the callback returns the default param, and I can selectively set `include` while retaining the rest.

**Comment by theonastos** [comment]
Any luck here?

**Comment by mariedevweb** [comment]
Try adding  in your vite.config.ts, this allowed me to include my svg file without the ?react 
`plugins: [react(), svgr({
    include: '**/*.svg'
  })],`

**Comment by lazaro9318** [comment]
> Try adding in your vite.config.ts, this allowed me to include my svg file without the ?react `plugins: [react(), svgr({ include: '**/*.svg' })],`

This works like a charm, thank you!

**Comment by sanjarcode** [comment]
The following worked, finally:
```jsx
import svgr from "@svgr/rollup"; // `npm i -D @svgr/rollup` to install

// change params for svgr
plugins: [
    react(),
    svgr({ dimensions: true, svgo: false, typescript: false }),
  ],
```
