### ISSUE TITLE
Error with Yarn Berry

### ISSUE THREAD

**Issue by 20hertz** [pd4d10/vite-plugin-svgr#15]
## Current Behavior
> [plugin:vite:svgr] vite-plugin-svgr tried to access esbuild, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

## Possible Solution
Add esbuild to the manifest's dependencies field.

## Steps to reproduce the problem

  1. Use Yarn as package manager
     `yarn create vite [PROJECT_NAME] --template react`
  2. `yarn set version berry`
  3. Install and configure vite-plugin-svgr plugin (as per [instructions](https://github.com/pd4d10/vite-plugin-svgr/blob/main/README.md))
  4. Start dev server

## Possible Implementation
See PR #16 

## Specifications

  - vite-plugin-svgr 0.4.0
  - Yarn 3.0.1
  - Node 14.17.5

**Comment by 20hertz** [comment]
With the most common package managers (Yarn, pnpm, and npm), it's generally a good practice to formally list a project's dependencies in the manifest (package.json).  The reason is well explained here: https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies

**Comment by 20hertz** [comment]
Thought I'd chip in with a [PR](https://github.com/pd4d10/vite-plugin-svgr/pull/16)

**Comment by pd4d10** [comment]
Closing, refer to https://github.com/pd4d10/vite-plugin-svgr/pull/16
