### ISSUE TITLE
can't import public/ files with / path

### ISSUE THREAD

**Issue by andylacko** [pd4d10/vite-plugin-svgr#18]
[plugin:vite:svgr] ENOENT: no such file or directory, open '/logo.svg'

only works with 

`../public/logo.svg`

**Comment by pd4d10** [comment]
According the Vite doc [here](https://vitejs.dev/config/#publicdir), the `publicDir` is to serve as plain static assets, which should not be transformed.

So in you case I guess it's better to place it into the `src`

**Comment by andylacko** [comment]
🤷🏻‍♂️, we solved it that way, It makes sense, when you minify your assets

Thx for answer
