### ISSUE TITLE
Multiple default exports when using "ref: true"

### ISSUE THREAD

**Issue by Pulkownikfgs** [pd4d10/vite-plugin-svgr#24]
Using `ref: true` in `svgrOptions` causes build failure with the following message:

```
[VITE]   Multiple exports with the same name "default"
[VITE]   6  |  const ForwardRef = forwardRef(ReactComponent);
[VITE]   7  |  export default ForwardRef;
[VITE]   8  |  export default "/images/no-invitations.svg"
[VITE]      |         ^
```

This is happening because svgr outputs `export default ForwardRef` rather than `export default ReactComponent`, and the referenced code fails to replace default export:

https://github.com/pd4d10/vite-plugin-svgr/blob/c35bbdca2133c5f353fcdc90ee483c7d576dabff/src/index.ts#L28

**Comment by pd4d10** [comment]
The current implementation is string replacement, which is not a good idea indeed.

Just wondering how create-react-app did it, maybe we can refer to it?

**Comment by Pulkownikfgs** [comment]
@pd4d10

I've looked inside CRA and svgr/webpack loader. It appears they are passing the results of previous loader with `previousExport` arg into `convert` function. So if `previousExport` is something like `export default "static/media/logo.svg";`, svgr will output 
```
const ForwardRef = React.forwardRef(SvgComponent);
export default "static/media/logo.svg";
export { ForwardRef as ReactComponent };
```

This also works with `memo: true`;

I think we can use it to get both default export and named export with predictable name. I'll give a try in my PR later.
