### ISSUE TITLE
Support exporting React component as a default export instead of `ReactComponent`

### ISSUE THREAD

**Issue by Jinjiang** [pd4d10/vite-plugin-svgr#26]
Hi,

Thanks for the great plugin!

I just saw you intentionally replaced

https://github.com/pd4d10/vite-plugin-svgr/blob/c35bbdca2133c5f353fcdc90ee483c7d576dabff/src/index.ts#L28

into

https://github.com/pd4d10/vite-plugin-svgr/blob/c35bbdca2133c5f353fcdc90ee483c7d576dabff/src/index.ts#L29

Would like to know the reason and kindly ask whether it's possible to keep the original way (at least as an option).

Seems #2 already did that. But the PR is still open.

Thanks.

**Comment by pd4d10** [comment]
As we discussed in #2, since the default behavior in Vite is to export a string as default, we probably should not break it

**Comment by Jinjiang** [comment]
Well received. Thanks.
