### ISSUE TITLE
typescript vite config file error

### ISSUE THREAD

**Issue by definitelynottitus** [pd4d10/vite-plugin-svgr#28]
when I try to put this command:
```javascript
import svgrPlugin from 'vite-plugin-svgr'
```
in the vite.config.ts file, I get this error from the compiler:
```
Module '".../node_modules/vite-plugin-svgr/lib/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
[index.d.ts(9, 1): ]()This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```
although the error is not preventing the plugin to run but would still like to know how to get this resolved, thanks.

**Comment by 532758463** [comment]
You can solve it by：

tsconfig.json or  tsconfig.node.json 

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
```

**Comment by definitelynottitus** [comment]
> You can solve it by：
> 
> tsconfig.json or tsconfig.node.json
> 
> ```json
> {
>   "compilerOptions": {
>     "allowSyntheticDefaultImports": true
>   },
>   "include": ["vite.config.ts"]
> }
> ```

I put that into the tsconfig.node.json file and I no longer see the error. I first thought this was unnecessary because it was already in the tsconfig.json file, thanks.
