### ISSUE TITLE
It is not work when build.

### ISSUE THREAD

**Issue by Yukiniro** [pd4d10/vite-plugin-svgr#29]
When build my project. All svgs build in public.  Could i build svg inline not in public?
Here is my config.
```js
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import svgrPlugin from 'vite-plugin-svgr';

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [svgrPlugin(), react()],
});

```

**Comment by LiuZhenyan-Wuzhong** [comment]
How did you solve this problem?

**Comment by Yukiniro** [comment]
I didn't solve this problem because svg is already embedded in the compiled code. The svg in public does not affect the execution of my code
