### ISSUE TITLE
Vite 3 compatibility

### ISSUE THREAD

**Issue by andresgutgon** [pd4d10/vite-plugin-svgr#37]
## What?
Hi 👋  first of all thanks a lot for this plugin it's awesome. I had a question related with Vite 3 compatibility. 
How difficult would be to make this plugin compatible with v3 of Vite?

**Comment by pd4d10** [comment]
AFAIK, the only thing is to update the peer dependencies version to `2 || 3`, but I've not been testing it yet.

https://github.com/pd4d10/vite-plugin-svgr/blob/c982c299287b09ee68e26dc0a475c7fbaf07c20b/package.json#L37

PRs are welcome if you'd like to contribute

**Comment by andresgutgon** [comment]
Thanks @pd4d10 I made the PR : )

**Comment by pd4d10** [comment]
@vshab Published

**Comment by vshab** [comment]
Thank you!
