### ISSUE TITLE
`vite build` fails

### ISSUE THREAD

**Issue by jaybe78** [pd4d10/vite-plugin-svgr#42]
Hello,

for some reason `svgr` plugin fails with trying to build `production` build but works on dev.

I'm getting
```
[vite-plugin-svgr] ENOENT: no such file or directory, open '/Users/jb/Documents/bulbshare-web-app-react/assets/svgs/bulbshare-logo.svg?extractStyles&lang.svg'
```

**Comment by pd4d10** [comment]
Could you please provide a minimal reproduction?

**Comment by jaybe78** [comment]
After investigating, I think the issue is related to `vite-plugin-ssr`.
https://github.com/brillout/vite-plugin-ssr/issues/353

The issue is reproducible there if you are curious

Please pull https://github.com/jaybe78/vps-webpack5-redux-streaming-test/tree/jb/bug/import-server-side-breaks-svg
then npm run prod

**Comment by pd4d10** [comment]
It looks like the issue has been solved. Closing
