### ISSUE TITLE
SVGR Options & TypeScript

### ISSUE THREAD

**Issue by mfpopa** [pd4d10/vite-plugin-svgr#5]
@pd4d10 Thanks for creating the plugin. Works nicely and I like that I can use both the default export for the src/path of the svg and the named export for the React component.

I was wondering if you would accept a PR to enable the plugin users to pass SVGR options (e.g. `{ plugins: ['@svgr/plugin-svgo'] }`).

Also, I think the plugin should provide the typings to support this change to svg file imports. A simple `client.d.ts` with the typings suggested in #3 which is then added by the users to the `tsconfig.json` like `"types": ["vite/client", "vite-plugin-svgr/client"]` would be a solution.

**Comment by pd4d10** [comment]
> I was wondering if you would accept a PR to enable the plugin users to pass SVGR options (e.g. { plugins: ['@svgr/plugin-svgo'] }).

Sure. PR's welcome!

**Comment by pd4d10** [comment]
BTW, plugins like `svgo` are more suitable for use in production mode.

Perhaps we can make it built-in and decide when to use it by https://vitejs.dev/config/#conditional-config

**Comment by IanVS** [comment]
It looks like there are two PRs open to add svgr options: #11 and #13.

**Comment by pd4d10** [comment]
Fixed in v0.6.0. Thanks for @IanVS 's work!
