### ISSUE TITLE
Vite 4 Support

### ISSUE THREAD

**Issue by bdbvb** [pd4d10/vite-plugin-svgr#63]
Attempting to upgrade Vite to version 4. Seems vite-plugin-svgr only supports up to version 3.

```
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.6.0 || 3" from vite-plugin-svgr@2.2.2
npm ERR! node_modules/vite-plugin-svgr
npm ERR!   dev vite-plugin-svgr@"2.2.2" from the root project
```

---
Temporary workaround in package.json:

`"overrides": { "vite-plugin-svgr": { "vite": "4" } },`

**Comment by pd4d10** [comment]
Thanks for the feedback!

Published v2.3.0
