### ISSUE TITLE
SVG files are still included in output

### ISSUE THREAD

**Issue by reknih** [pd4d10/vite-plugin-svgr#69]
`vite` still outputs the SVG files that `svgr` converted into React components in the final output. Because the SVGs are already stored within the JavaScript, it would be nice to suppress the additional file outputs.

**Comment by soaresluciano** [comment]
I managed to avoid the svg files to be emitted using the [rollup-plugin-no-emit](https://github.com/Arnesfield/rollup-plugin-no-emit)
My config looks like this:
 `    plugins: [
      svgr({
        exportAsDefault: true,
      }),
      noEmit({ match: (file) => file.endsWith('.svg') }),
      react(),
    ],`
   
   It's not ideal, but it gets the job done util this option is not available.
   I hope it helps you.

**Comment by lukashaertel** [comment]
We've been working on this issue ourselves. Our solution is to amend this plugin in the following way.

```ts
import type {Plugin} from 'vite'
import basePlugin, {ViteSvgrOptions} from 'vite-plugin-svgr'

interface ViteSvgToJsxOptions extends ViteSvgrOptions {
    includeSvgAssets?: boolean;
}

function svgToJsx(
    {
        exportAsDefault,
        svgrOptions,
        esbuildOptions,
        include = '**/*.svg',
        exclude,
        includeSvgAssets,
    }: ViteSvgToJsxOptions): Plugin {
    // Create own filter instance to prevent assets from being emitted.
    const filter = createFilter(include, exclude);

    // Create plugin from base.
    const plugin = basePlugin({
        exportAsDefault,
        svgrOptions,
        esbuildOptions,
        include,
        exclude
    });

    // Update name, set enforce to pre if no SVG assets should be emitted, set load to capture files that match filter.
    plugin.name = 'vite-plugin-svg-to-jsx';
    plugin.enforce = !includeSvgAssets ? 'pre' : undefined;
    plugin.load = (id) => !includeSvgAssets && filter(id) ? "" : null;
    return plugin;
}
```

By enforcing the plugin to run in `'pre'` and returning a non-null value for load, the standard asset plugin will no longer include the SVG in the assets. This has so far been the cleanest way, as the load step still has the full path to work with and match the filters against, as opposed to removing the SVG from the bundle.

I think that adding the option and `enforce` and `load` properties is a simple inclusion to fix this issue.

**Comment by woodreamz** [comment]
Could be really nice to fix this issue :) A PR seems ready.

**Comment by EwenDC** [comment]
> I managed to avoid the svg files to be emitted using the [rollup-plugin-no-emit](https://github.com/Arnesfield/rollup-plugin-no-emit) My config looks like this: ` plugins: [ svgr({ exportAsDefault: true, }), noEmit({ match: (file) => file.endsWith('.svg') }), react(), ],`
> 
> It's not ideal, but it gets the job done util this option is not available. I hope it helps you.

If TypeScript yells at you when you try to add noEmit to the plugin list, it's because that package has Rollup 2 as a peer dependency, when the latest version of Vite is using Rollup 3. The plugin itself is actually perfectly compatible with Rollup 3 however, so you can just tell your package manager of choice to resolve the dependency as such. For example, when using pnpm you can add the following to your package.json:

```javascript
  "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "rollup-plugin-no-emit>rollup": "3"
      }
    }
  },
```

**Comment by mattsputnikdigital** [comment]
Any news with this?

**Comment by mattsputnikdigital** [comment]
@lukashaertel do you know why, when using your solution, I get the following error?

```
import { ReactComponent as Chevron } from 'modules/theme/images/icons/button/chevron.svg';

error during build:
RollupError: "ReactComponent" is not exported by "src/modules/theme/images/icons/button/chevron.svg", imported by "src/components/shared/Button/index.tsx".

```

**Comment by pd4d10** [comment]
See https://github.com/pd4d10/vite-plugin-svgr/pull/71#issuecomment-1727006445

**Comment by EwenDC** [comment]
> See [#71 (comment)](https://github.com/pd4d10/vite-plugin-svgr/pull/71#issuecomment-1727006445)

I'm still seeing the SVG's being output in the build folder, regardless of how I configure include/exclude. Those options seem to control what files get transformed but not what files get included in the final output.

**Comment by pd4d10** [comment]
@EwenDC Thanks for the feedback! Indeed, we should set `enforce: pre` to override the built-in `vite:asset` plugin's behavior.

Would you please try the latest v4.1.0?

**Comment by EwenDC** [comment]
> @EwenDC Thanks for the feedback! Indeed, we should set `enforce: pre` to override the built-in `vite:asset` plugin's behavior.
> 
> Would you please try the latest v4.1.0?

Hey! Apologies for the slow response. I can confirm that the latest version resolves the issue. Thank you!

**Comment by woodreamz** [comment]
I also confirm it's fixed!

Thanks :)

**Comment by mikepink** [comment]
Hello, this ended up being a breaking change for us since SVGs were no longer present in the build manifest generated by Vite. We mitigated by downgrading to v4.0.0.
