### ISSUE TITLE
Cannot find module 'esbuild'

### ISSUE THREAD

**Issue by IanVS** [pd4d10/vite-plugin-svgr#8]
It looks like my only esbuild is inside `node_modules/vite/node_modules`, and so this plugin cannot find it and throws `Cannot find module 'esbuild'`. I'm using npm@7.17.0.

**Comment by pd4d10** [comment]
Does this issue still exist?

**Comment by IanVS** [comment]
I initially worked around it by adding `esbuild` to my direct project dependencies.  I just tried removing it and rebuilding my node_modules, and for whatever reason esbuild is now being hoisted to the top-level.  So I guess maybe this isn't an issue.  I'll close for now until/unless I or others experience a problem in the future.
