### ISSUE TITLE
EsLint "Unable to resolve path to module" error in version 4.0

### ISSUE THREAD

**Issue by kolorfilm** [pd4d10/vite-plugin-svgr#91]
I get a typescript error when try to import a svg like this:

`import Close from './close.svg?react';`

_ESLint: Unable to resolve path to module './close.svg?react'.(import/no-unresolved)_

**Comment by chrismeyers** [comment]
This is an ESLint error, not a TypeScript error.  It looks related to this issue: https://github.com/import-js/eslint-plugin-import/issues/1739

The workaround that I'm using is to just omit the querystring by reverting the `include` pattern to what it was before:

```js
// vite.config.js
import { defineConfig } from 'vite';
import svgr from 'vite-plugin-svgr';

export default defineConfig({
  plugins: [svgr({ include: '**/*.svg' })],
});
```

Then you can import without `?react`:

```js
import Close from './close.svg';
```

**Comment by kolorfilm** [comment]
@chrismeyers thanks for your answer. This helped. I prefer the first version.

Unfortunately my jest transformer doesn't work anymore. Previously my jest snapshots were generated like that for an svg that was imported like that:

`import { ReactComponent as Close } from './close.svg';`

In the snapshot the svg looked like that: 

```
<svg
  className="closeIcon"
  data-testid="closeIcon"
  onClick={[Function]}
>
  close.svg
</svg>
```

After I changed the import to: `import Close from './close.svg';` the snapshot generates the svg like that:

```
<close.svg
    className="closeIcon"
    data-testid="closeIcon"
    onClick={[Function]}
</>
```

what is wrong and not a valid svg. :-(

**Comment by kolorfilm** [comment]
It seems also that I cannot add properties to the component in jsx:

<Close className={styles.closeIcon} onClick={onClose} data-testid={dataTestIdAttr} />

gives me a TS error:

```
TS2322: Type
{   className: string;   onClick: () => void;   "data-testid": string | undefined; }
is not assignable to type  IntrinsicAttributes 
Property  className  does not exist on type  IntrinsicAttributes 
```

**Comment by DevPowers** [comment]
@chrismeyers  Using the proposal of :
```
plugins: [svgr({ include: '**/*.svg' })],
```

When importing the SVG, the IDE thinks I am importing a string and not a component giving Typescript errors.

**Comment by chrismeyers** [comment]
@DevPowers Maybe try setting `declare module "*.svg"` somewhere in your project to what it was before ([see client.d.ts diff](https://github.com/pd4d10/vite-plugin-svgr/commit/18a4e266478f35e10893045d393825ca5ce11a12))?

**Comment by kolorfilm** [comment]
@DevPowers yeah what @chrismeyers said:

you can add something like:

```
declare module '*.svg' {
  import * as React from 'react';

  const ReactComponent: React.FunctionComponent<React.ComponentProps<'svg'> & { title?: string }>;

  export default ReactComponent;
}
```

to you `vite-env.d.ts` file.

**Comment by DevPowers** [comment]
That got rid of the import warning but when using the SVG component I am still getting issues "Property  style  does not exist on type  IntrinsicAttributes"

I am using the component like this, and passing style to control the height and width of the SVG image: 

```
<SvgComponent
            aria-label="Logo"
            style={{
                height,
                width
            }}
        />
```

For now I can use the eslint ignore option and just import using the ?react option, but it seems a bit hacky. Would be nice if it played nice with typescript and eslint out of the box

**Comment by issam-seghir** [comment]
using this `plugin: [svgr({ include: '**/*.svg' })],` in vite config works great for me,
i don't need to use ` ?react `syntax anymore, thanks
