### ISSUE TITLE
"ReactComponent" is not exported after update to 4.0.0

### ISSUE THREAD

**Issue by jewe11er** [pd4d10/vite-plugin-svgr#92]
Hi! I'm using `import { ReactComponent as ArrowDown } from './ArrowDown.svg'`. Everything was okay before update to 4.0.0. Now I get an error:
`RollupError: "ReactComponent" is not exported by "src/libs/icons/thin/ArrowDown.svg", imported by "src/libs/icons/index.ts".`
How can I resolve it?

**Comment by Tbaut** [comment]
Can confirm, having the same issue. Reverted to v3.3

**Comment by lnhrdt** [comment]
I just ran into this as well. Thanks for the tip @Tbaut.

@pd4d10 I see a breaking change on [the 4.0.0 releases tag](https://github.com/pd4d10/vite-plugin-svgr/releases/tag/v4.0.0) but the only explanation is "Export as default with query" with a link to the commit. It's a little hard to understand the intention of the change as it relates to the named `ReactComponent` export. Was it a mistake to remove the named export? Or is the only option for accessing the react component going forward to use the default export with the query?

**Comment by pd4d10** [comment]
@lnhrdt Hi, sorry, the release log might not be that clear.

Background here: https://github.com/pd4d10/vite-plugin-svgr/pull/71#issuecomment-1727006445

**Comment by lnhrdt** [comment]
Got it @pd4d10! Thank you for the clarification, and for maintaining this library. 🍻

**Comment by binaryartifex** [comment]
has anyone got this working in the context of an NX monorepo? Ive got library-a, with a bunch of svg's, imported into a barrel index that is the entry point for the lib thats consumed by app-a. following suggestions mentioned here and it just flat refuses to work

**Comment by tcdw** [comment]
If you are using WebStorm and has a lot of SVG icons to migrate, you can mass-replace all of them with regex mode enabled.

From:

```text
\{ ReactComponent as (.+) } from (.+).svg
```

To:

```text
$1 from $2.svg?react
```

**Comment by JodyAndrews** [comment]
> has anyone got this working in the context of an NX monorepo? Ive got library-a, with a bunch of svg's, imported into a barrel index that is the entry point for the lib thats consumed by app-a. following suggestions mentioned here and it just flat refuses to work

Did you get this working? I'm having the same issue

**Comment by ZebraFlesh** [comment]
Same issue with an nx monorepo, I keep getting errors like: 

```
 >  NX   [vite]: Rollup failed to resolve import "@my-compant/assets/svg/logo.svg?react" from "/Users/me/git/my-project/layout/src/LayoutLogo/LayoutLogo.tsx".
```

I tried to make a minimum viable repo, but my nx skills are not up to task.

**Comment by JodyAndrews** [comment]
In regards to NX. I think this started failing in commit: 18a4e266478f35e10893045d393825ca5ce11a12

Overriding the include back to what it was seems to be working for me

svgr({ include: '**/*.svg' })

**Comment by bruteF04C3** [comment]
Just in case anyone's still stuck on this even after adding `?react` at the end of the asset path, you probably just need to ensure two things:

1. The **vite.config.ts** has the following configuration in place
    `
    svgr({include: ["**/*.svg"]})
`
2.  If TS complains about missing module or type declarations, you need to add the following (preferably in a **custom.d.ts** file)
  <code>declare module "*.svg?react" {
  import React from "react";
  const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
  export default ReactComponent;
  }</code>
