### ISSUE TITLE
Compatibility of version 4.0 and jest

### ISSUE THREAD

**Issue by pcorpet** [pd4d10/vite-plugin-svgr#97]
I use jest for my test and it's choking on the new syntax introduced in 4.0 (Resource Queries). Jest themselves are planning on [supporting it](https://github.com/jestjs/jest/pull/6282) but the PR is not moving and it has been a while.

Do you have an idea on how I could make the upgrade to v4 and keep my jest tests? Maybe there's a way to make the resource query syntax optional?

**Comment by denchen** [comment]
This may or may not help you, but I end up mocking out my SVGs in Jest.

```javascript
jest.mock('svgs/MySvg.svg', () =>
  () => <div title="mock-svg" />
);
```

**Comment by denchen** [comment]
So I was able to find a workaround with a combination of two things:

1. Install [babel-plugin-import-remove-resource-query](https://github.com/hkjorgensen/babel-plugin-import-remove-resource-query) and add the plugin to your Jest babel config
2. In your test, mock out the SVG:
   ```javascript
   jest.mock('/path/to/your/image.svg', () => () => <div className="mock-svg" />);
   ```

**Comment by pcorpet** [comment]
Thanks I've made it worked. Note that I've used a generic transform in my jest config so that I didn't need to mock each svg.

The solution that worked for me:

1. Install [babel-plugin-import-remove-resource-query](https://github.com/hkjorgensen/babel-plugin-import-remove-resource-query) and add the plugin to your Jest babel config (thank you @denchen !)
2. Update my `jest.config.js` file with a:
```js
transform: {
  '^.+\\.svg$': `<rootDir>/jest/__mocks__/svg.js`,
}
```
3. and then the content of this `svg.js` file:
```js
module.exports = {
	process() {
		return {
			code: 'module.exports = () => null;',
		}
	},
	getCacheKey() {
		// The output is always the same.
		return 'svgTransformSvgr4'
	},
}
```

**Comment by denchen** [comment]
@pcorpet Your solution is much nicer. I did have a bit of a hiccup where my tests were still failing with trying to load the SVG, but it was due to a caching problem. I ran Jest once with `--no-cache`, and it fixed the issue.

**Comment by mmirus** [comment]
After some trial and error, I went about making v4 work with jest in a different way that _seems_ to be working.

In `jest.config.ts`:

```ts
import type { Config } from '@jest/types';

const config: Config.InitialOptions = {
  // ...
  moduleNameMapper: {
    // ...
    '^(.+\\.svg)\\?react$': '<rootDir>/src/__mocks__/svg.tsx',
  },
  // ...
};

module.exports = config;

```

In `src/__mocks__/svg.tsx`:

```tsx
import React from 'react';

const SvgrMock = React.forwardRef<HTMLSpanElement>((props, ref) => (
  <span ref={ref} {...props} />
));
SvgrMock.displayName = 'SvgrMock';

export const ReactComponent = SvgrMock;
export default SvgrMock;

```

**Comment by josegoval** [comment]
> After some trial and error, I went about making v4 work with jest in a different way that _seems_ to be working.
> 
> In `jest.config.ts`:
> 
> ```ts
> import type { Config } from '@jest/types';
> 
> const config: Config.InitialOptions = {
>   // ...
>   moduleNameMapper: {
>     // ...
>     '^(.+\\.svg)\\?react$': '<rootDir>/src/__mocks__/svg.tsx',
>   },
>   // ...
> };
> 
> module.exports = config;
> ```
> 
> In `src/__mocks__/svg.tsx`:
> 
> ```tsx
> import React from 'react';
> 
> const SvgrMock = React.forwardRef<HTMLSpanElement>((props, ref) => (
>   <span ref={ref} {...props} />
> ));
> SvgrMock.displayName = 'SvgrMock';
> 
> export const ReactComponent = SvgrMock;
> export default SvgrMock;
> ```

I had to add also `"^(.+\\.svg)$": "<rootDir>/src/__mocks__/svg.tsx",`. Here is my `moduleNameMapper`:

```
"moduleNameMapper": {
      "^(.+\\.svg)\\?react$": "<rootDir>/src/__mocks__/svg.tsx",
      "^(.+\\.svg)$": "<rootDir>/src/__mocks__/svg.tsx",
}
```

**Comment by jarosik10** [comment]
I've come up with some other idea.
1. Add moduleNameMapper to help jest with handling this import syntax: `.svg?react`. It converts imports like `./icons/myIcon.svg?react` to `./icons.myIcons.svg`

```js
  moduleNameMapper: {
    '^(.*).svg\\?react$': '$1.svg',
  }
  ```

2. Add trasformer `jest-transformer-svg` . ` '^.+\\.svg(\\?react)?$'` - it uses 'jest-transformer-svg' for normal `.svg` imports and also `.svg?react`.

```js
  transform: {
    '^.+\\.svg(\\?react)?$': 'jest-transformer-svg',
  },
  ```
  
  
  With this setup svgs are rendered like this:
  ```
  <svg
     class="opt-icon icon iconSmall moreIcon"
     data-file-name="SvgMore_vert24px"
  />
```
